telegram_bot:
  http_client: psr18.guzzle_client
  request_factory: nyholm.psr7.psr17_factory
  stream_factory: nyholm.psr7.psr17_factory
  api_token: '%env(string:TG_API_TOKEN)%'
  webhook:
    url: '%env(resolve:TG_WEBHOOK)%'