parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    psr18.guzzle_client:
      class: GuzzleHttp\Client
      arguments:
        - http_errors: false

    psr17.guzzle_factory:
      class: GuzzleHttp\Psr7\HttpFactory

    Symfony\Component\Serializer\Encoder\JsonEncoder:
        class: Symfony\Component\Serializer\Encoder\JsonEncoder
        tags:
            - { name: Symfony\Component\Serializer\Serializer, priority: -995 }

    Symfony\Component\Serializer\Normalizer\ObjectNormalizer:
        class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer
        tags:
            - { name: Symfony\Component\Serializer\Serializer, priority: -995 }

    telegramUserDataTransfomer:
        class: App\DataTransformer\TGUserDataTransformer

    telegramUserRepository:
        class: App\Repository\TelegramUserRepository

    manager:
        class: App\Manager\Manager

    telegramUserManager:
        class: App\Manager\TelegramUserManager
        arguments:
          $transformer: "@telegramUserDataTransfomer"
          $repository: "@telegramUserRepository"
          $manager: "@manager"

    App\Controller\StartCommandController:
        class: App\Controller\StartCommandController
        arguments:
          $manager: "@telegramUserManager"

    telegramBotApiProvider:
      class: Luzrain\TelegramBotApi\BotApi
      arguments:
        $requestFactory: "@nyholm.psr7.psr17_factory"
        $streamFactory: "@nyholm.psr7.psr17_factory"
        $client: "@psr18.guzzle_client"
        $token: '%env(string:TG_API_TOKEN)%'

    telegramImageService:
        class: App\Service\TelegramImageService
        arguments:
          $botApiProvider: "@telegramBotApiProvider"

    imageManager:
        class: App\Manager\ImageManager
        arguments:
          $telegramImageService: "@telegramImageService"
          $userRepository: "@telegramUserRepository"
          $manager: "@manager"

    App\Controller\PhotoMessageController:
          class: App\Controller\PhotoMessageController
          arguments:
            $manager: "@imageManager"
