parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    psr18.guzzle_client:
      class: GuzzleHttp\Client
      arguments:
        - http_errors: false

    psr17.guzzle_factory:
      class: GuzzleHttp\Psr7\HttpFactory

    Symfony\Component\Serializer\Encoder\JsonEncoder:
        class: Symfony\Component\Serializer\Encoder\JsonEncoder
        tags:
            - { name: Symfony\Component\Serializer\Serializer, priority: -995 }

    Symfony\Component\Serializer\Normalizer\ObjectNormalizer:
        class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer
        tags:
            - { name: Symfony\Component\Serializer\Serializer, priority: -995 }

    telegramUserDataTransfomer:
        class: App\DataTransformer\TGUserDataTransformer

    telegramUserRepository:
        class: App\Repository\TelegramUserRepository

    manager:
        class: App\Manager\Manager

    telegramUserManager:
        class: App\Manager\TelegramUserManager
        arguments:
          $transformer: "@telegramUserDataTransfomer"
          $repository: "@telegramUserRepository"
          $manager: "@manager"

    App\Controller\StartCommandController:
        class: App\Controller\StartCommandController
        arguments:
          $manager: "@telegramUserManager"

#    App\Controller\MainController:
#        class: App\Controller\MainController
#        arguments:
#          $manager: "@telegramUserManager"
